// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8lguvNEGIfA-q_RMLC6kFbZxR59KF3Xo',
    appId: '1:235720163543:web:cd167165bed221a7a67092',
    messagingSenderId: '235720163543',
    projectId: 'movies-ec3ff',
    authDomain: 'movies-ec3ff.firebaseapp.com',
    storageBucket: 'movies-ec3ff.firebasestorage.app',
    measurementId: 'G-7LB6MSBRY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUr36RyTebjxrArToKCPqfJD7FHhVQMBo',
    appId: '1:235720163543:android:7db35f4e45d274bda67092',
    messagingSenderId: '235720163543',
    projectId: 'movies-ec3ff',
    storageBucket: 'movies-ec3ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW3TSxiZG3HqXX9Lz3zxY_HgLnQWvXYbA',
    appId: '1:235720163543:ios:1e2f713ba02349e8a67092',
    messagingSenderId: '235720163543',
    projectId: 'movies-ec3ff',
    storageBucket: 'movies-ec3ff.firebasestorage.app',
    iosBundleId: 'com.example.movie2Application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW3TSxiZG3HqXX9Lz3zxY_HgLnQWvXYbA',
    appId: '1:235720163543:ios:1e2f713ba02349e8a67092',
    messagingSenderId: '235720163543',
    projectId: 'movies-ec3ff',
    storageBucket: 'movies-ec3ff.firebasestorage.app',
    iosBundleId: 'com.example.movie2Application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8lguvNEGIfA-q_RMLC6kFbZxR59KF3Xo',
    appId: '1:235720163543:web:6130afd7c8511aa5a67092',
    messagingSenderId: '235720163543',
    projectId: 'movies-ec3ff',
    authDomain: 'movies-ec3ff.firebaseapp.com',
    storageBucket: 'movies-ec3ff.firebasestorage.app',
    measurementId: 'G-NRMGW3YLS4',
  );
}
